//
// PoseDetectionPluginRegistrar.m
// Auto-generated by withMediaPipePose config plugin
//
#import <VisionCamera/FrameProcessorPlugin.h>
#import <VisionCamera/FrameProcessorPluginRegistry.h>
#import "LoadManagerPro-Swift.h"

VISION_EXPORT_SWIFT_FRAME_PROCESSOR(PoseDetectionPlugin, detectPose)
