/**
 * Expo Config Plugin — MediaPipe Pose Detection via Vision Camera
 *
 * This plugin configures the iOS build to:
 * 1. Add MediaPipeTasksVision CocoaPod
 * 2. Copy the Swift frame processor plugin to the Xcode project
 * 3. Generate the Obj-C registration file with correct module name
 * 4. Copy the pose_landmarker_full.task model to bundle resources
 *
 * PREREQUISITES:
 * - Run: node scripts/download-pose-model.js (downloads the .task model)
 * - The model must exist at assets/models/pose_landmarker_full.task
 */

const {
  withDangerousMod,
  withXcodeProject,
} = require('@expo/config-plugins');
const path = require('path');
const fs = require('fs');

function withMediaPipePose(config) {
  // ─── Step 0: Ensure ios.useFrameworks = static in Podfile.properties.json ───
  // MediaPipeTasksVision REQUIRES use_frameworks! to generate Swift module maps.
  // Without this, Xcode fails with: "no such module 'MediaPipeTasksVision'"
  config = withDangerousMod(config, [
    'ios',
    (modConfig) => {
      const propsPath = path.join(
        modConfig.modRequest.platformProjectRoot,
        'Podfile.properties.json'
      );

      let props = {};
      if (fs.existsSync(propsPath)) {
        try {
          props = JSON.parse(fs.readFileSync(propsPath, 'utf-8'));
        } catch (e) {
          console.warn('[withMediaPipePose] Could not parse Podfile.properties.json, creating new');
        }
      }

      if (props['ios.useFrameworks'] !== 'static') {
        props['ios.useFrameworks'] = 'static';
        fs.writeFileSync(propsPath, JSON.stringify(props, null, 2));
        console.log('[withMediaPipePose] Set ios.useFrameworks = static');
      }

      return modConfig;
    },
  ]);

  // ─── Step 1: Add MediaPipeTasksVision pod to Podfile ───
  config = withDangerousMod(config, [
    'ios',
    (modConfig) => {
      const podfilePath = path.join(
        modConfig.modRequest.platformProjectRoot,
        'Podfile'
      );

      if (!fs.existsSync(podfilePath)) {
        console.warn('[withMediaPipePose] Podfile not found, skipping pod injection');
        return modConfig;
      }

      let podfile = fs.readFileSync(podfilePath, 'utf-8');

      if (!podfile.includes('MediaPipeTasksVision')) {
        // Insert after use_expo_modules! (standard Expo anchor)
        podfile = podfile.replace(
          /use_expo_modules!/,
          "use_expo_modules!\n  pod 'MediaPipeTasksVision'"
        );
        fs.writeFileSync(podfilePath, podfile);
        console.log('[withMediaPipePose] Added MediaPipeTasksVision pod');
      }

      return modConfig;
    },
  ]);

  // ─── Step 2: Copy native files + model, add to Xcode project ───
  config = withXcodeProject(config, (modConfig) => {
    const xcodeProject = modConfig.modResults;
    const projectRoot = modConfig.modRequest.projectRoot;
    const platformProjectRoot = modConfig.modRequest.platformProjectRoot;
    const projectName = modConfig.modRequest.projectName;

    const targetDir = path.join(platformProjectRoot, projectName);

    // Ensure target dir exists
    if (!fs.existsSync(targetDir)) {
      fs.mkdirSync(targetDir, { recursive: true });
    }

    // ── Copy Swift plugin ──
    const swiftSrc = path.join(projectRoot, 'plugins', 'ios', 'PoseDetectionPlugin.swift');
    const swiftDest = path.join(targetDir, 'PoseDetectionPlugin.swift');
    if (fs.existsSync(swiftSrc)) {
      fs.copyFileSync(swiftSrc, swiftDest);
      console.log('[withMediaPipePose] Copied PoseDetectionPlugin.swift');
    } else {
      console.error('[withMediaPipePose] PoseDetectionPlugin.swift not found at', swiftSrc);
    }

    // ── Generate Obj-C registrar with correct module name ──
    const moduleName = projectName.replace(/[^a-zA-Z0-9_]/g, '');
    const objcContent = `//
// PoseDetectionPluginRegistrar.m
// Auto-generated by withMediaPipePose config plugin
//
#import <VisionCamera/FrameProcessorPlugin.h>
#import <VisionCamera/FrameProcessorPluginRegistry.h>
#import "${moduleName}-Swift.h"

VISION_EXPORT_SWIFT_FRAME_PROCESSOR(PoseDetectionPlugin, detectPose)
`;
    const objcDest = path.join(targetDir, 'PoseDetectionPluginRegistrar.m');
    fs.writeFileSync(objcDest, objcContent);
    console.log('[withMediaPipePose] Generated PoseDetectionPluginRegistrar.m (module:', moduleName + ')');

    // ── Copy pose model if available ──
    const modelSrc = path.join(projectRoot, 'assets', 'models', 'pose_landmarker_full.task');
    const modelDest = path.join(targetDir, 'pose_landmarker_full.task');
    if (fs.existsSync(modelSrc)) {
      fs.copyFileSync(modelSrc, modelDest);
      console.log('[withMediaPipePose] Copied pose_landmarker_full.task');
    } else {
      console.warn('[withMediaPipePose] Model not found at', modelSrc);
      console.warn('[withMediaPipePose] Run: node scripts/download-pose-model.js');
    }

    // ── Add files to Xcode project ──
    try {
      // Find app group by iterating PBXGroup objects directly
      const groups = xcodeProject.hash.project.objects['PBXGroup'] || {};
      let appGroupKey = null;
      for (const [key, val] of Object.entries(groups)) {
        if (typeof val === 'object' && val.name === projectName) {
          appGroupKey = key;
          break;
        }
      }

      if (!appGroupKey) {
        // Fallback: use main group
        appGroupKey = xcodeProject.getFirstProject().firstProject.mainGroup;
      }

      const targetUuid = xcodeProject.getFirstTarget().uuid;

      // Add Swift source
      if (fs.existsSync(swiftDest)) {
        xcodeProject.addSourceFile(
          `${projectName}/PoseDetectionPlugin.swift`,
          { target: targetUuid },
          appGroupKey
        );
      }

      // Add Obj-C source
      xcodeProject.addSourceFile(
        `${projectName}/PoseDetectionPluginRegistrar.m`,
        { target: targetUuid },
        appGroupKey
      );

      // Add model as resource
      if (fs.existsSync(modelDest)) {
        // Ensure "Resources" PBXGroup exists (Expo projects don't create it by default)
        // Without this, addResourceFile crashes on correctForResourcesPath
        if (!xcodeProject.pbxGroupByName('Resources')) {
          xcodeProject.addPbxGroup([], 'Resources');
        }
        xcodeProject.addResourceFile(
          `${projectName}/pose_landmarker_full.task`,
          { target: targetUuid },
          appGroupKey
        );
      }

      console.log('[withMediaPipePose] Added files to Xcode project');
    } catch (e) {
      console.warn('[withMediaPipePose] Xcode project manipulation warning:', e.message);
      console.warn('[withMediaPipePose] Files are copied — add manually to Xcode if needed');
    }

    return modConfig;
  });

  return config;
}

module.exports = withMediaPipePose;
